manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: damex
      url-base: https://github.com/damex
    - name: charlesmst
      url-base: https://github.com/charlesmst
    
  projects:
    - name: zmk
      remote: charlesmst
      revision: feat/deskhop-sync
      import: app/west.yml
    - name: zmk-feature-split-esb
      remote: damex
      revision: v0.5.1
      import: true
  self:
    path: config
