name: Build ZMK firmware
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@v0.3

    steps:
      - name: Debug
        run: |
          cd /tmp/zmk-config
          west list
          echo "--- mbedtls path ---"
          find . -name "pk.c" 2>/dev/null | head -5
          echo "--- oberon path ---"
          find . -name "oberon_helpers.c" 2>/dev/null | head -5